language: java

compiler:
  - gcc

jdk:
  - oraclejdk8

env:
  - OPENCV_HOME=$HOME/opencv OPENCV_JAVA_PATH=$OPENCV_HOME/share/OpenCV/java

cache:
  directories:
    - $OPENCV_HOME

install:
  - cd $HOME
  - git clone git://github.com/Itseez/opencv.git --branch 3.1.0 --depth=1
  - cd opencv
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=$OPENCV_HOME ..
  - make -j4
  - make install
  - cd $TRAVIS_BUILD_DIR

script:
  - ./gradlew clean test
